[project]
name = "vod-downloader"
version = "1.0.0"
description = ""
authors = [{ name = "aoqia", email = "aoqia@aoqia.dev" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirerpy>=0.3.4",
    "keyring>=25.7.0",
    "pycryptodomex>=3.23.0",
    "yt-dlp",
]

[tool.uv.sources]
yt-dlp = { git = "https://github.com/c-basalt/yt-dlp", rev = "rplaylive" }
